package com.epam.task6.logic;

public enum CommandName {
	REGISTER_COMMAND, LOGIN_COMMAND, NO_SUCH_COMMAND, GET_USER_PAGE_COMMAND, SIGN_IN_COMMAND, REGISTER_NEW_USER_COMMAND, CHANGE_LANGUAGE_COMMAND
}
