package com.epam.task6.logic;

public enum CommandName {
	REGISTER_COMMAND,
	LOGIN_COMMAND,
	NO_SUCH_COMMAND,
	GET_USER_PAGE_COMMAND,
	SIGN_IN_COMMAND,
	SIGN_OUT_COMMAND,
	REGISTER_NEW_USER_COMMAND,
	CHANGE_LANGUAGE_COMMAND,
	CREATE_CLAIM_COMMAND,
	SEND_CLAIM_COMMAND,
	CREATE_DATABASE_COMMAND,
	DELETE_DATABASE_COMMAND,
	CREATE_ASSIGNATION_COMMAND,
	REGISTER_ASSIGNATION_COMMAND,
	DELETE_ASSIGNATION_COMMAND
}
